---
name: test

releases:
- name: python
  version: create
  url: file:///Users/pivotal/workspace/python-release

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: python
  azs: [z1]
  instances: 1
  jobs:
  - name: python-3.8-test
    release: python
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
